### ISSUE TITLE
Question on identifying novel isoforms 

### ISSUE THREAD

**Issue by josiegleeson** [MurphyDavid/TX2P#3]
Hello, I had a quick question regarding the analysis. Thanks for the tool, its really easy to use and we're looking at novel isoforms in brain so it will be useful for us to test some of them with public MS data. I really enjoyed reading your recent pre-print.

I was wondering if by including the known UniProt reference as contaminants (as mentioned in your readme) will this help identify only the novel portions of my isoforms? 

Let's say I have a novel isoform of a gene that encodes this ORF (novel section enclosed with {}):
>novel_tx_1
MESEQLFH{CPGWSPTPGLKQ}RGYYRNSY

And the annotated protein in UniProt is:
>known
MESEQLFHRGYYRNSY

Would including the UniProt reference as contaminants mean that only peptides mapping to a portion of the novel section {CPGWSPTPGLKQ} would be returned, and peptides mapping to shared sections in both the novel and known proteins would be classed as contaminants and discarded?

Also, does only including a small number of potential novel protein sequences (say 100) at a time do anything to the false positive rates of peptide identification?

Thanks so much for any help or advice on this!

**Comment by MurphyDavid** [comment]
Hi


Metamorphous doesn't really distinguish between contaminants and the sequences you're searching for.  It's why they're fed into the tool with the same options. When it finds peptides that match to one or more input sequences it lists all that match. 


So in your example, if it found a peptide "ESEQLFHCPGWS" it would list it as only matching novel_tx_1

novel_tx_1           ESEQLFHCPGWS

Assuming it didn't perfectly match anything else in the input protein list. 

If it found "ESEQLFH" it would list it as 

novel_tx_1|known                   ESEQLFH

When I'm looking for novel isoforms I tend to discard any rows in the results that include any sequences from my "contaminants" list [AKA the uniprot reviewed proteins] 

For this reason I include a unique prefix to all the sequences I'm interested in as it makes filtering easier. 

Re: false positive rate, metamorpheus does a q-value calculation based on the size of the input dataset  the AllQuantifiedProteinGroups.tsv file it generates includes a qvalue for each peptide group found quantifying how likely it is to be found by chance in a dataset of that size.  I choose to discard anything with a qvalue higher than 0.01, or about 1% which appears to be a fairly normal cutoff in papers using mass spec data.  If you have a set of sequences of interest I'd lean towards searching for them together to let the tool handle it as one calculation.

Hope this helps
David

[Minor Disclaimer in regards to any questions about the behaviour of metamorpheus: I'm not a maintainer of Metamorpheus and even after a few years using it and trawling through it's docs I may make mistakes,]

**Comment by josiegleeson** [comment]
Hi David,

Thanks for the prompt reply. 

Ok great, I'll basically include the normal reference proteins then, and filter the output for peptide mappings only containing novel IDs, not novel and known IDs. Does that sound correct? 

What do you think would happen if I in-silico digested my novel isoforms and just included the novel portion...? That way I could potentially not worry about providing the reference proteome alongside it and then having to filter the results. It might also be a bit quicker.
For example:
>novel_tx_1_fragment
ESEQLFHCPGWS

If that doesn't sound like a good way of doing things or you're unsure, no worries. Thanks again, that's been really helpful.

**Comment by MurphyDavid** [comment]
It would definitely be far far faster but there would be disadvantages. On very large mass spec datasets it can take more than a week to run when we're running a search when we include the whole proteome.

But there are some disadvantages to cutting down the input. If, for example, there was evidence in the mass spec data for  a peptide "ESEQLFHCPGWSP" but you had excluded everything except the novel section then it would be missed. 

You'd also need to check whether any sub-sequences of your novel region 7 amino acids or longer matched anything else in the human proteome 

So for example if you were interested in CPGWSPTPGLKQ but there was some random protein in uniprot with a subsequence like GWSPTPGL that you didn't include as a contaminant then it might return a match for your novel protein but actually it's picking up something from that other gene.

**Comment by josiegleeson** [comment]
Ok that makes sense, I think we'll continue using the original proteome as well then.

Thanks for your help, I really appreciate it!
